name: "build with ufbt"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'
  schedule: 
    # do a build every Sunday to keep up with SDK changes
    - cron: "0 0 * * 0"
jobs:
  ufbt-build-action:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: Official Dev channel
            sdk-channel: dev
          - name: Official Release channel
            sdk-channel: release
          - name: Unleashed Dev
            sdk-index-url: https://up.unleashedflip.com/directory.json
            sdk-channel: dev
          - name: Unleashed Release
            sdk-index-url: https://up.unleashedflip.com/directory.json
            sdk-channel: release
    name: 'fap ufbt build for ${{ matrix.name }}'
    env:
      UNLEASHED_FIRMWARE: ${{ matrix.sdk-index-url == 'https://up.unleashedflip.com/directory.json' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build with ufbt
        uses: flipperdevices/flipperzero-ufbt-action@v0.1.2
        id: build-app
        with:
          sdk-channel: ${{ matrix.sdk-channel }}
          sdk-index-url: ${{ matrix.sdk-index-url }}
          ufbt-args: "${{ env.UNLEASHED_FIRMWARE == '1' && '--extra-define -DUNLEASHED_FIRMWARE' || '-s' }}" # -s by default
      - name: Upload app artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}-${{ steps.build-app.outputs.suffix }}-build
          path: ${{ steps.build-app.outputs.fap-artifacts }}
